app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'IndexController@index');
Route::get('/home', 'IndexController@index');


// Authentication routes...
Route::get('auth/', 'Auth\AuthController@index');
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');


// Compte
Route::get('/compte', array (
    'uses' => 'CompteController@index'
));
Route::get('/compte/modifier', array (
    'uses' => 'CompteController@edit'
));
Route::post('/compte/modifier', array (
    'uses' => 'CompteController@update'
));
Route::get('/compte/avatar', array (
    'uses' => 'CompteController@avatar'
));
Route::post('/compte/avatar', array (
    'uses' => 'CompteController@Postavatar'
));
Route::get('/compte/avatar/use/{id}', array (
    'uses' => 'CompteController@changeAvatar'
));
//info tooltip
Route::get('/info-tooltip/{id}', array (
    'uses' => 'ProfilController@infoTooltip',
));



// bajail
Route::get('/bajail', array (
    'uses' => 'BajailController@index'
));
Route::get('/bajail/charte', array (
    'uses' => 'BajailController@index_charte'
));
Route::get('/bajail/regles', array (
    'uses' => 'BajailController@index_regles'
));




// admin
Route::get('/bajail/admin', array (
    'uses' => 'BajailController@index_admin'
));
Route::get('/bajail/admin/devenir-admin', array (
    'uses' => 'DevenirAdminController@index'
));
Route::post('/bajail/admin/devenir-admin', array (
    'uses' => 'DevenirAdminController@post'
));
Route::get('/bajail/admin/devenir-admin/confirmation', array (
    'uses' => 'DevenirAdminController@confirmation',
    'middleware' => 'auth'
));




// test des règles
Route::get('/bajail/regles/test', array (
    'uses' => 'BajailController@index_test',
    'middleware' => 'auth'
));
Route::post('/bajail/regles/test', array (
    'uses' => 'BajailController@verifTest',
    'middleware' => 'auth'
));



// vocal
Route::get('/tchat', array (
    'uses' => 'tchatController@index'
));


// vip
Route::get('/bajail/vip', array (
    'uses' => 'VipController@index'
));

Route::post('/bajail/vip/confirmation', array (
    'uses' => 'VipController@store',
    'middleware' => 'auth'
));


// nems
Route::get('/team-nems', array (
    'uses' => 'NemsController@index'
));
Route::get('/team-nems/liste', array (
    'uses' => 'NemsController@liste'
));


// promo
Route::get('/promo', array (
    'uses' => 'PromoController@index'
));
// promo
Route::get('/promo/acheter/{id}', array (
    'uses' => 'PromoController@acheter',
    'middleware' => 'auth'
));

Route::get('/promo/acheter/{id}/valider', array (
    'uses' => 'PromoController@valider',
    'as' => 'acheterPromo',
    'middleware' => 'auth'
));



//steamid
Route::get('/compte/steamid', array (
    'uses' => 'CompteController@steamid',
    'middleware' => 'auth'
));

Route::post('/compte/steamid', array (
    'uses' => 'CompteController@steamidPost',
    'middleware' => 'auth'
));

Route::post('/compte/steamid/verif', array (
    'uses' => 'CompteController@steamidVerif',
    'middleware' => 'auth'
));


//profil
Route::get('/profil/{id}-{name}', array (
    'uses' => 'ProfilController@index',
    'as' => 'userProfil'
));



//jetons
Route::get('/jetons', array (
    'uses' => 'JetonsController@index',
));
Route::any('/jetons/check', array (
    'uses' => 'JetonsController@check',
));
Route::get('/jetons/valide', array (
    'uses' => 'JetonsController@valide',
));
Route::any('/jetons/valide2', array (
    'uses' => 'JetonsController@validestarpass',
));
Route::get('/jetons/erreur', array (
    'uses' => 'JetonsController@erreur',
));
Route::get('/jetons/paypal-trait', array (
    'uses' => 'JetonsController@checkPaypal',
));
Route::post('/jetons/paypal-trait', array (
    'uses' => 'JetonsController@checkPaypal',
));
Route::post('/jetons/valide-paypal', array (
    'uses' => 'JetonsController@validePaypal',
));


// coins
Route::get('/coins', array (
    'uses' => 'CoinsController@index',
));
Route::post('/coins', array (
    'uses' => 'CoinsController@post',
));



Route::group(['middleware' => ['auth']], function () {
    //forum, liste des forums
    Route::get('/forum', array (
        'uses' => 'ForumController@index'
    ));
// liste des forum dans une categorie
    Route::get('/forum/category/{id}-{name}', array (
        'uses' => 'ForumController@topicsList',
        'as' => 'forumCategory'
    ));

// créer un topic dans une catégorie
    Route::get('/forum/category/{id}-{name}/create', array (
        'uses' => 'ForumController@createTopic',
        'as' => 'createTopic',
        'middleware' => 'auth'
    ));
    Route::post('/forum/category/{id}-{name}/create', array (
        'uses' => 'ForumController@createTopicPost',
        'as' => 'createTopicPost',
        'middleware' => 'auth'
    ));


// affiche un topic
    Route::get('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}', array (
        'uses' => 'ForumController@topics',
        'as' => 'forumTopic'
    ));
// répondre par ajax a un topic (quick reply)
    Route::post('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}', array (
        'uses' => 'ForumController@replyTopicFast',
        'as' => 'forumTopic'
    ));

// lock topic
    Route::get('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}/lock', array (
        'uses' => 'ForumController@lockTopic',
        'as' => 'lockTopic',
        'middleware' => 'auth'
    ));

// pinned un topic
    Route::get('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}/pinned', array (
        'uses' => 'ForumController@pinnedTopic',
        'as' => 'pinnedTopic',
        'middleware' => 'auth'
    ));


// affiche la page de réponse normale a un topic
    Route::get('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}/reply', array (
        'uses' => 'ForumController@replyTopics',
        'as' => 'replyTopic',
        'middleware' => 'auth'
    ));
// répondre normalement a un topic
    Route::post('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}/reply', array (
        'uses' => 'ForumController@postReplyTopics',
        'middleware' => 'auth',
        'as' => 'replyTopicPost'
    ));


// répondre a un post en particulier d'un topic
    Route::get('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}/reply/{post_id}', array (
        'uses' => 'ForumController@replyTopicsWithQuote',
        'as' => 'replyTopicWithQuote',
        'middleware' => 'auth'
    ));

    Route::post('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}/reply/{post_id}', array (
        'uses' => 'ForumController@postReplyTopics',
        'middleware' => 'auth'
    ));


// modifier le post d'un topic
    Route::get('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}/edit/{post_id}', array (
        'uses' => 'ForumController@EditPost',
        'as' => 'EditPost',
        'middleware' => 'auth'
    ));
// modifier le post d'un topic
    Route::post('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}/edit/{post_id}', array (
        'uses' => 'ForumController@EditPostSend',
        'as' => 'EditPostSend',
        'middleware' => 'auth'
    ));


    // supprime un post
    Route::get('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}/remove/{post_id}', array (
        'uses' => 'ForumController@RemovePost',
        'as' => 'removePost',
        'middleware' => 'auth'
    ));
});

app/ForumPosts.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use tidy;

class ForumPosts extends Model
{
    public function user()
    {
        return $this->belongsTo('App\User','users_id');
    }

    public function forum_topics()
    {
        return $this->belongsTo('App\ForumTopics','forum_topics_id','');
    }

    public function getDateAttribute(){
        $date = new Carbon($this->created_at);
        return $date->format('d/m/Y').' à '.$date->format('H:i');
    }
    public function getDateShortAttribute(){
        $date = new Carbon($this->created_at);
        return $date->format('d/m/Y');
    }

    public function getUpdatedAtAttribute($value){
        $date = new Carbon($value);
        return $date->format('d/m/Y').' à '.$date->format('H:i');
    }
    public function getMessageShortAttribute(){
        return $this->get_words($this->message);
    }

    function get_words($sentence, $count = 50) {
        $pieces = explode(" ", $sentence);
        $first_part = implode(" ", array_splice($pieces, 0, $count)).'...';
        $tidy = new Tidy();
        $tidy->parseString($first_part);
        $tidy->cleanRepair();

        echo $tidy;
    }
}

resources/views/index.blade.php
@extends('layout/index')

@section('title') www.nemesis-spirit.com @endsection


@section('content')


    <!-- <div class="content-padding">
        <a href="podcasts-single.html" class="top-alert-message">
            <span><span class="pod-live">Custom message</span>An event is happening tonight 20:00! Be Prepared!</span>
        </a>
    </div> -->

    <h2><span>Les dernières news</span></h2>
    <div class="content-padding">
        <div class="home-article left">
            @if(count($news) > 0)
                <span class="article-image-out">
                    <span class="image-comments"><span>{{ count($news[0]->forum_posts) }}</span></span>
                    <span class="article-image">
                        <a href="{{ route('forumTopic',[1,'News',$news[0]->id,str_slug($news[0]->title)]) }}">{!! HTML::image('images/news.png') !!}</a>
                    </span>
                </span>
                <h3><a href="{{ route('forumTopic',[1,'News',$news[0]->id,str_slug($news[0]->title)]) }}">{{$news[0]->title}}</a></h3>
                {!! $news_first_post->message_short !!}
                <div>
                    <a href="{{ route('forumTopic',[1,'News',$news[0]->id,str_slug($news[0]->title)]) }}" class="defbutton"><i class="fa fa-reply"></i>Lire en entier</a>
                </div>
            @endif
        </div>
        <div class="home-article right">
            <ul>
                <?php $i=0; ?>
                @foreach($news as $topic)
                    @if($i != 0)
                        <li>
                            <a href="post.html">
                                <span class="image-comments"><span>{{ count($topic->forum_posts) }}</span></span>
                                {!! HTML::image('images/news4.png') !!}
                                <strong>{{ $topic->title }}</strong>
                                <span class="a-txt">En savoir plus sur cette news</span>
                            </a>
                        </li>
                    @endif
                    <?php $i++; ?>
                @endforeach
            </ul>

        </div>
        <div class="clear-float"></div>
    </div>


    <h2><span>Les derniers topics du forum</span></h2>
    <div class="content-padding">

        <div class="podcast-list">
            @foreach($last_topics as $last_topic)
                <a href="{{ route('forumTopic',[$last_topic->forum_category->id,str_slug($last_topic->forum_category->nom),$last_topic->id,str_slug($last_topic->title)]) }}" class="item">
                    <span class="podcast-li-nr">{!! $last_topic->created_at !!}</span>
                    <span class="podcast-li-title">{{ $last_topic->title }}</span>
                    <span class="podcast-li-time">Posté par : <br/>{{ $last_topic->users->pseudo }}</span>
                </a>
            @endforeach
        </div>

    </div>

    <h2><span>Les dernières actions effectuées</span></h2>

    <div class="content-padding">

        <div class="podcast-list">
            @foreach($historiques as $historique)
                <div class="item">
                    <span class="podcast-li-type">
                        @if($historique->type == 'inscription')
                            {!! HTML::image('images/user_small.png') !!}
                        @elseif($historique->type == 'vip')
                            {!! HTML::image('images/king-icon_small.png') !!}
                        @elseif($historique->type == 'admin')
                            {!! HTML::image('images/admin_small.png') !!}
                        @elseif($historique->type == 'forum_news')
                            {!! HTML::image('images/news_small.png') !!}
                        @elseif($historique->type == 'forum_topic')
                            {!! HTML::image('images/talk_small.png') !!}
                        @endif
                    </span>
                    <span class="podcast-li-date">{{ $historique->created_at }}</span>
                    <span class="podcast-li-desc">
                        @if($historique->type == 'inscription')
                            <strong>{{$historique->users->pseudo}}</strong> s'est inscrit sur le site Nemesis Spirit
                        @elseif($historique->type == 'vip')
                            <strong>{{$historique->users->pseudo}}</strong> est devenu VIP sur notre serveur
                        @elseif($historique->type == 'admin')
                            <strong>{{$historique->users->pseudo}}</strong> est devenu Admin sur notre serveur
                        @elseif($historique->type == 'forum_news')
                            <strong>{{$historique->users->pseudo}}</strong> a crée une news.
                        @elseif($historique->type == 'forum_topic')
                            <strong>{{$historique->users->pseudo}}</strong> a créer un topic dans le forum
                        @endif
                    </span>
                </div>
            @endforeach
        </div>


        <br/>
        <a href="{{url('/tchat')}}">{!! HTML::image('images/Discord_présentation1.png','discord',['class' => 'responsive-img']) !!}</a>
        <br/><br/>
        <h4>Discord</h4>
        Envie de discuter avec les NemS et les habitués ? <br/>
        <br/>
        Discord est une application qui permet de discuter par écrit ou par vocal. <br/>
        <br/>
        C'est un combiné de Skype et de Teamspeak <br/>
        Pas besoin d'avoir le logiciel, un simple navigateur web suffit ! <br/>
        <br/>
        <a class="button" href="{{url('/tchat')}}">Tester Discord</a>

    </div>









@endsection