app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'IndexController@index');
Route::get('/home', 'IndexController@index');


// Authentication routes...
Route::get('auth/', 'Auth\AuthController@index');
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');


// Compte
Route::get('/compte', array (
    'uses' => 'CompteController@index'
));
Route::get('/compte/modifier', array (
    'uses' => 'CompteController@edit'
));
Route::post('/compte/modifier', array (
    'uses' => 'CompteController@update'
));
Route::get('/compte/avatar', array (
    'uses' => 'CompteController@avatar'
));
Route::post('/compte/avatar', array (
    'uses' => 'CompteController@Postavatar'
));
Route::get('/compte/avatar/use/{id}', array (
    'uses' => 'CompteController@changeAvatar'
));
//info tooltip
Route::get('/info-tooltip/{id}', array (
    'uses' => 'ProfilController@infoTooltip',
));



// bajail
Route::get('/bajail', array (
    'uses' => 'BajailController@index'
));
Route::get('/bajail/charte', array (
    'uses' => 'BajailController@index_charte'
));
Route::get('/bajail/regles', array (
    'uses' => 'BajailController@index_regles'
));




// admin
Route::get('/bajail/admin', array (
    'uses' => 'BajailController@index_admin'
));
Route::get('/bajail/admin/devenir-admin', array (
    'uses' => 'DevenirAdminController@index'
));
Route::post('/bajail/admin/devenir-admin', array (
    'uses' => 'DevenirAdminController@post'
));
Route::get('/bajail/admin/devenir-admin/confirmation', array (
    'uses' => 'DevenirAdminController@confirmation',
    'middleware' => 'auth'
));




// test des règles
Route::get('/bajail/regles/test', array (
    'uses' => 'BajailController@index_test',
    'middleware' => 'auth'
));
Route::post('/bajail/regles/test', array (
    'uses' => 'BajailController@verifTest',
    'middleware' => 'auth'
));



// vocal
Route::get('/tchat', array (
    'uses' => 'tchatController@index'
));


// vip
Route::get('/bajail/vip', array (
    'uses' => 'VipController@index'
));

Route::post('/bajail/vip/confirmation', array (
    'uses' => 'VipController@store',
    'middleware' => 'auth'
));


// nems
Route::get('/team-nems', array (
    'uses' => 'NemsController@index'
));
Route::get('/team-nems/liste', array (
    'uses' => 'NemsController@liste'
));


// promo
Route::get('/promo', array (
    'uses' => 'PromoController@index'
));
// promo
Route::get('/promo/acheter/{id}', array (
    'uses' => 'PromoController@acheter',
    'middleware' => 'auth'
));

Route::get('/promo/acheter/{id}/valider', array (
    'uses' => 'PromoController@valider',
    'as' => 'acheterPromo',
    'middleware' => 'auth'
));



//steamid
Route::get('/compte/steamid', array (
    'uses' => 'CompteController@steamid',
    'middleware' => 'auth'
));

Route::post('/compte/steamid', array (
    'uses' => 'CompteController@steamidPost',
    'middleware' => 'auth'
));

Route::post('/compte/steamid/verif', array (
    'uses' => 'CompteController@steamidVerif',
    'middleware' => 'auth'
));


//profil
Route::get('/profil/{id}-{name}', array (
    'uses' => 'ProfilController@index',
    'as' => 'userProfil'
));



//jetons
Route::get('/jetons', array (
    'uses' => 'JetonsController@index',
));
Route::any('/jetons/check', array (
    'uses' => 'JetonsController@check',
));
Route::get('/jetons/valide', array (
    'uses' => 'JetonsController@valide',
));
Route::any('/jetons/valide2', array (
    'uses' => 'JetonsController@validestarpass',
));
Route::get('/jetons/erreur', array (
    'uses' => 'JetonsController@erreur',
));
Route::get('/jetons/paypal-trait', array (
    'uses' => 'JetonsController@checkPaypal',
));
Route::post('/jetons/paypal-trait', array (
    'uses' => 'JetonsController@checkPaypal',
));
Route::post('/jetons/valide-paypal', array (
    'uses' => 'JetonsController@validePaypal',
));


// coins
Route::get('/coins', array (
    'uses' => 'CoinsController@index',
));
Route::post('/coins', array (
    'uses' => 'CoinsController@post',
));



Route::group(['middleware' => ['auth']], function () {
    //forum, liste des forums
    Route::get('/forum', array (
        'uses' => 'ForumController@index'
    ));
// liste des forum dans une categorie
    Route::get('/forum/category/{id}-{name}', array (
        'uses' => 'ForumController@topicsList',
        'as' => 'forumCategory'
    ));

// créer un topic dans une catégorie
    Route::get('/forum/category/{id}-{name}/create', array (
        'uses' => 'ForumController@createTopic',
        'as' => 'createTopic',
        'middleware' => 'auth'
    ));
    Route::post('/forum/category/{id}-{name}/create', array (
        'uses' => 'ForumController@createTopicPost',
        'as' => 'createTopicPost',
        'middleware' => 'auth'
    ));


// affiche un topic
    Route::get('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}', array (
        'uses' => 'ForumController@topics',
        'as' => 'forumTopic'
    ));
// répondre par ajax a un topic (quick reply)
    Route::post('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}', array (
        'uses' => 'ForumController@replyTopicFast',
        'as' => 'forumTopic'
    ));

// lock topic
    Route::get('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}/lock', array (
        'uses' => 'ForumController@lockTopic',
        'as' => 'lockTopic',
        'middleware' => 'auth'
    ));

// pinned un topic
    Route::get('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}/pinned', array (
        'uses' => 'ForumController@pinnedTopic',
        'as' => 'pinnedTopic',
        'middleware' => 'auth'
    ));


// affiche la page de réponse normale a un topic
    Route::get('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}/reply', array (
        'uses' => 'ForumController@replyTopics',
        'as' => 'replyTopic',
        'middleware' => 'auth'
    ));
// répondre normalement a un topic
    Route::post('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}/reply', array (
        'uses' => 'ForumController@postReplyTopics',
        'middleware' => 'auth',
        'as' => 'replyTopicPost'
    ));


// répondre a un post en particulier d'un topic
    Route::get('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}/reply/{post_id}', array (
        'uses' => 'ForumController@replyTopicsWithQuote',
        'as' => 'replyTopicWithQuote',
        'middleware' => 'auth'
    ));

    Route::post('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}/reply/{post_id}', array (
        'uses' => 'ForumController@postReplyTopics',
        'middleware' => 'auth'
    ));


// modifier le post d'un topic
    Route::get('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}/edit/{post_id}', array (
        'uses' => 'ForumController@EditPost',
        'as' => 'EditPost',
        'middleware' => 'auth'
    ));
// modifier le post d'un topic
    Route::post('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}/edit/{post_id}', array (
        'uses' => 'ForumController@EditPostSend',
        'as' => 'EditPostSend',
        'middleware' => 'auth'
    ));


    // supprime un post
    Route::get('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}/remove/{post_id}', array (
        'uses' => 'ForumController@RemovePost',
        'as' => 'removePost',
        'middleware' => 'auth'
    ));
});

app/User.php
<?php

namespace App;

use App\MyClass\NemSClass;
use Carbon\Carbon;
use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Illuminate\Support\Facades\Auth;

class User extends Model implements AuthenticatableContract,
                                    AuthorizableContract,
                                    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded  = ['id'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];

    protected $_serversAdmins = [];
    protected $_birthday_sql;

    public function usersAction()
    {
        return $this->hasMany('App\usersAction');
    }

    public function serversAdmins()
    {
        return $this->hasMany('App\serversAdmins');
    }

    public function getAdminFinAttribute(){
        if(empty($this->_serversAdmins)){
            $this->_serversAdmins = $this->serversAdmins->first();
        }
        return $this->_serversAdmins->date_fin;
    }

    public function getTypeDroitAttribute(){
        if(empty($this->_serversAdmins)){
            $this->_serversAdmins = $this->serversAdmins->first();
        }
        if($this->_serversAdmins->droit_fun){
            return 'Fun';
        }
        else{
            return 'Normal';
        }
    }
    public function getJeuxAttribute(){
        $jeux = [];
        if($this->jeux_css == 'on'){
            $jeux[] = 'images/icon_css.png';
        }
        if($this->jeux_csgo == 'on'){
            $jeux[] = 'images/icon_csgo.png';
        }
        if($this->jeux_lol == 'on'){
            $jeux[] = 'images/icon_lol.png';
        }
        return $jeux;
    }

    public function getVipFinFrAttribute(){
        $date = new Carbon($this->vip_fin);
        return $date->format('d/m/Y');
    }

    public function getVipDebutFrAttribute(){
        $date = new Carbon($this->vip_debut);
        return $date->format('d/m/Y');
    }

    public function getBirthdaySqlAttribute(){
        $this->birthday; // on simule l'appel de cet attribut
        return $this->_birthday_sql;
    }

    public function getBirthdayAttribute($value){
        $this->_birthday_sql = $value;
        if($value != null) {
            $timestamp = strtotime($value);
            $date = Carbon::createFromTimestamp($timestamp);
            return $date->format('d/m/Y');
        }
        else{
            return '';
        }
    }

    public function getSteamProfilAttribute(){
        return NemSClass::steamid_to_url($this->steamid);
    }

    public function getIsOnlineAttribute(){

        $online = Online::where('users_id',$this->id)->where('last_activity','>',strtotime('-15 min'))->first();

        if($online == null) return false;
        return true;
    }



}

resources/views/compte/avatar.blade.php
@extends('layout/singlepage')

@section('title','Modifier mon avatar')
@section('sub_pagename','Mon Compte')
@section('sub_pagename_link',url('/compte'))
@section('pagename','Modifier mon avatar')


@section('content')

    <h2>Modifier mon avatar</h2>

    <div class="content-padding">

        <div class="row">

            @if(Session::has('modifierAvatar'))
                <div class="info-message" style="background-color: #75a226;">
                    <p>Votre avatar a été modifié avec succès</p>
                </div>
            @endif

            @include('messages/error')
            @include('messages/success')

            <a class="defbutton" href="{{url('/compte')}}">
                <i class="fa fa-arrow-left"></i>
                Revenir a la gestion de mon compte
            </a>


            <h3>Choisir un avatar existant</h3>
            <br/>
            <p>Si tu ne sais pas quel avatar mettre, tu peux choisir l'un des avatar suivant : </p>
            <br/>


            @for ($i = 1; $i <= 20; $i++)
                <a class="avatar-demo" href="{{url('/compte/avatar/use',$i)}}">
                    <img src="{{url('/')}}/uploads/tux{{$i}}.png" alt=""/>
                </a>
            @endfor

            <br/>
            <h3>Uploader mon avatar</h3>
            <br/>

            {!! Form::open(array('files' => true)) !!}

                <div class="btn-file">
                    <div class="btn-file-left"></div>
                    <div class="btn-file-btn">
                        <input id="images_file" type="file" multiple="true" name="file">
                        <div>
                            <i class="fa fa-file "></i>
                            Parcourir...
                        </div>

                    </div>
                </div>

                <br/><br/>
                <button style="background-color: #DB6D1D;" class="button" type="submit">Uploader mon image</button>

            {!! Form::close() !!}


        </div>

    </div>


@endsection

resources/views/compte/index.blade.php
@extends('layout/singlepage')

@section('title','Mon Compte')
@section('pagename','Mon Compte')


@section('content')

    <div class="signup-panel">
        <div class="left">
            <h2>Mon profil</h2>

            <div class="content-padding">
                <div class="center-align">
                    @if($user->avatar == null)
                        {!! HTML::image('/uploads/tux-counter.png','',['class' => 'img-responsive']) !!}
                    @else
                        <img src="{{url('/')}}/uploads/{{$user->avatar}}" alt="{{$user->pseudo}} avatar"/>
                    @endif
                    <br/><br/>
                </div>

                <ul class="profile-info">
                    <li>
                        <span class="first">Login</span>
                        <span class="last">{{$user->login}}</span>
                    </li>
                    <li>
                        <span class="first">Pseudo</span>
                        <span class="last">{{$user->pseudo}}</span>
                    </li>
                    <li>
                        <span class="first">Email</span>
                        <span class="last">{{$user->email}}</span>
                    </li>
                    <li>
                        <span class="first">Steamid</span>
                        <span class="last"><a target="_blank" href="http://steamcommunity.com/profiles/{{$user->steam_profil}}">{{$user->steamid}}</a></span>
                    </li>
                    <li>
                        <span class="first">Steamid3</span>
                        <span class="last">{{$user->steamid3}}</span>
                    </li>
                    <li>
                        <span class="first">Pays</span>
                        <span class="last">{{$user->pays}}</span>
                    </li>
                    <li>
                        <span class="first">Date de naissance</span>
                        <span class="last">{{$user->birthday}}</span>
                    </li>
                    <li>
                        <span class="first">Jeux</span>
                        <span class="last">
                            @foreach($user->jeux as $jeux)
                                {!! HTML::image($jeux) !!}
                            @endforeach
                        </span>
                    </li>
                </ul>

                <a class="newdefbutton" href="{{url('/compte/avatar')}}">
                    <i class="fa fa-picture-o"></i>
                    Changer mon avatar
                </a>

                <br/><br/>

                <a class="newdefbutton" href="{{url('/compte/modifier')}}">
                    <i class="fa fa-wrench"></i>
                    Modifier mon profil
                </a>

                <br/><br/>

                <a class="newdefbutton" href="{{url('/compte/steamid')}}">
                    <i class="fa fa-wrench"></i>
                    Modifier mon steamid
                </a>

                <br/><br/>

                <a class="newdefbutton" href="{{url('/auth/logout')}}">
                    <i class="fa fa-sign-out"></i>
                    Me déconnecter
                </a>

            </div>
        </div>
        <div class="right">
            <h2>Informations</h2>


            <div class="info-blocks">
                <ul style="margin-left: 50px">
                    <li>
                        <a class="info-block" href="{{ url('/jetons') }}">
                            <b>{{$user->jetons}}</b>
                            <span>Jetons</span>
                        </a>
                    </li>
                    <li>
                        <a class="info-block" href="{{ url('/coins') }}">
                            <b>{{$user->coins}}</b>
                            <span>Coins</span>
                        </a>
                    </li>
                </ul>
            </div>

            <div class="clear-float do-the-split"></div>

            <h3>Status sur les serveurs :</h3>
            <br/>
            <h4>Admin :</h4>
            <br/>
            @if($user->is_admin)
                <ul class="fa-ul" style="margin-bottom: 30px">
                    <li><i class="fa-li fa fa-angle-double-right"></i> Tu est actuellement admin <br/></li>
                    <li><i class="fa-li fa fa-angle-double-right"></i> Type de droit : <strong>{{ $user->type_droit }}</strong> <br/></li>
                    <li><i class="fa-li fa fa-angle-double-right"></i> Date de fin : <strong>{{ $user->admin_fin }}</strong> <br/></li>
                </ul>
                <a class="defbutton" href="{{ url('/bajail/admin') }}">
                    <i class="fa fa-cogs"></i>
                    Gérer mes droits admin
                </a>

            @else
                Tu n'es pas admin sur notre serveur. <br/>
                <br/>
                <a class="defbutton" href="{{ url('/bajail/admin') }}">
                    <i class="fa fa-cogs"></i>
                    Devenir admin
                </a>
            @endif
            <br/>
            <h4>VIP :</h4>
            <br/>
            @if($user->is_vip)
                <ul class="fa-ul" style="margin-bottom: 30px">
                    <li><i class="fa-li fa fa-angle-double-right"></i> Tu est VIP sur le Bajail <br/></li>
                    <li><i class="fa-li fa fa-angle-double-right"></i> Grade actuel : <strong>{{ $user->vip_grade }}</strong> <br/></li>
                    <li><i class="fa-li fa fa-angle-double-right"></i> Date de fin : <strong>{{ $user->vip_fin_fr }}</strong> <br/></li>
                </ul>
                <a class="defbutton" href="{{ url('/bajail/vip') }}">
                    <i class="fa fa-cogs"></i>
                    Gérer mes droits vip
                </a>

            @else
                Tu n'es pas vip sur notre serveur. <br/>
                <br/>
                <a class="defbutton" href="{{ url('/bajail/vip') }}">
                    <i class="fa fa-cogs"></i>
                    Devenir vip
                </a>
            @endif




        </div>
    </div>

    <div class="clear-float"></div>

    <div class="breaking-line"></div>


@endsection

resources/views/compte/modifier.blade.php
@extends('layout/singlepage')

@section('title','Modifier mon profil')
@section('sub_pagename','Mon Compte')
@section('sub_pagename_link',url('/compte'))
@section('pagename','Modifier mon profil')


@section('content')

    <h2>Modifier mon profil</h2>

    <div class="content-padding">

        <div class="row">

            @include('messages/errors')

            @include('messages/success')

            {!! Form::model($user) !!}

            <div class="input-field col s12">
                {!! Form::text('login', null ,['readonly']) !!}
                {!! Form::label('Login') !!}
            </div>

            <div class="input-field col s12">
                {!! Form::text('email') !!}
                {!! Form::label('Email') !!}
            </div>

            <div class="input-field col s6">
                {!! Form::password('password') !!}
                {!! Form::label('Password') !!}
            </div>

            <div class="input-field col s6">
                {!! Form::password('password_confirmation') !!}
                {!! Form::label('Password comfirmation') !!}
            </div>

            <div class="input-field col s12">
                {!! Form::text('pseudo') !!}
                {!! Form::label('Pseudo') !!}
            </div>

            <div class="input-field col s12">
                {!! Form::select('pays', array('France' => 'France', 'Belgique' => 'Belgique', 'Suisse' => 'Suisse', 'Autres' => 'Autres')) !!}
                {!! Form::label('Pays') !!}
            </div>

            <div class="input-field col s12">
                {!! Form::text('birthday', $user->birthday, ['id' => 'birthday']) !!}
                {!! Form::label('birthday') !!}
            </div>

            <div class="col s4">
                {!! Form::checkbox('jeux_css', $user->jeux_css, 0,  ['id' => 'jeux_css']) !!}
                {!! Form::label('jeux_css') !!}
            </div>

            <div class="col s4">
                {!! Form::checkbox('jeux_csgo', $user->jeux_csgo, 0,  ['id' => 'jeux_csgo']) !!}
                {!! Form::label('jeux_csgo') !!}
            </div>

            <div class="col s4">
                {!! Form::checkbox('jeux_lol', $user->jeux_lol, 0,  ['id' => 'jeux_lol']) !!}
                {!! Form::label('jeux_lol') !!}
            </div>

            <div class="input-field col s12">
                <div class="clear-float do-the-split"></div>
            </div>

            <div class="input-field col s12">
                <button class="btn waves-effect waves-light" type="submit" name="action">Modifier mon profil</button>
            </div>

            <div class="input-field col s12">
                <a class="btn waves-effect waves-light" href="{{url('/compte/steamid')}}" >Je veux modifier mon steamid</a>
            </div>



            {!! Form::close() !!}

        </div>

    </div>


@endsection

resources/views/compte/steamid.blade.php
@extends('layout/singlepage')

@section('title','Gérer mon steamid')
@section('sub_pagename','Mon Compte')
@section('sub_pagename_link',url('/compte'))
@section('pagename','Steamid')


@section('content')

    <h2>Gérer son steamid</h2>

    <div class="content-padding">

        <div class="row">

            @if(isset($success))
                <div class="info-message" style="background-color: #75a226;">
                    <p>{{ $success }}</p>
                </div>
            @endif

            @include('messages/error')

            @if(Session::has('need_steamid'))
                <div class="info-message">
                    <p>{{ Session::get('need_steamid') }}</p>
                </div>
            @endif




            {!! Form::open() !!}

                <p>Pour être Admin ou VIP, vous devez indiquer votre steamid.</p>
                <p>Celui-ci permet de vous identifier sur le serveur</p>

                @if($user->steamid != null)
                    <div class="cadreGreen">
                        <p><strong>SteamID actuel</strong> : {{ $user->steamid }}</p>
                        <p><strong>Steamid3 actuel</strong> : {{ $user->steamid3 }}</p>
                    </div>
                @endif

                <strong>Comment trouver son steamid ?</strong> <br/>
                <br/>

                <ul class="fa-ul">
                    <li><i class="fa-li fa fa-angle-double-right"></i> Accédez à votre page profil Steam (Steam > Votre pseudo > Profil)</li>
                    <li><i class="fa-li fa fa-angle-double-right"></i> Copier L'url qui est indiqué sous le menu</li>
                </ul>
            <br/>

                {!! HTML::image('images/steamcommunity.jpg') !!}
            <br/><br/>
            <b>Convertir le lien :</b> <br/>

                    <div class="input-field">
                        {!! Form::text('steamcommunity', null, ['required' => 'required']) !!}
                        <label for="">Indiquer votre lien</label>
                    </div>

            <div id="checksteamid" class="button">Verifier mon lien</div>

            <div class="show-infos-player" style="display: none">
                <br/>
                <br/>
                <strong>Est-ce votre profil ?</strong> <br/>
                <br/>
                <div class="col s4">
                    <img src="" alt=""/>
                </div>
                <div class="col s8">
                    <strong>Pseudo : </strong><span class="pseudo"></span> <br/>
                    <strong>Steamid : </strong><span class="steamid"></span> <br/>
                    <strong>Steamid3 : </strong><span class="steamid3"></span> <br/>
                    <br/>
                    <button type="submit" style="background-color: #519623;" class="button">Je confirme qu'il s'agit de mon profil</button>
                </div>
            </div>
                <div class="player-not-found" style="display:none">
                    <br/><br/>
                    <div class="info-message" style="background-color: #a24026;">
                        <p>Désolé, nous ne parvenons pas a trouver votre compte. <br/>
                            Votre url doit ressembler a celle-ci : http://steamcommunity.com/profiles/76561197985522057
                            <br/><br/>
                        Ce site peut éventuellement vous aider : <a href="https://steamid.io/lookup" target="_blank">https://steamid.io/lookup</a></p>
                    </div>
                </div>


            {!! Form::close() !!}

        </div>

    </div>


@endsection

resources/views/compte/user_tooltip.blade.php
<div class="user-tooltip-info">
    <a href="{{ route('userProfil',['name' => str_slug($info_user->pseudo), 'id' => $info_user->id]) }}" class="username">{{ $info_user->pseudo }}</a>
    <a href="{{ route('userProfil',['name' => str_slug($info_user->pseudo), 'id' => $info_user->id]) }}" class="avatar @if($info_user->isOnline) online @endif ">
                                            <span class="wrapimg" style="background-color:#fff;">
                                                @if($info_user->avatar == null)
                                                    {!! HTML::image('/uploads/tux-counter.png','',['class' => 'img-responsive','width' => '90', 'height' => '90']) !!}
                                                @else
                                                    <img src="{{url('/')}}/uploads/{{$info_user->avatar}}" alt="{{$info_user->pseudo}} avatar" width="90" height="90"  />
                                                @endif
                                            </span>
    </a>
    <div class="info">
        <div>
            <font>Status:</font>
            @if($info_user->is_nems)<span class="admin-ribbon">NemS</span> @endif
            @if($info_user->is_admin)<span class="admin-ribbon">Admin</span> @endif
            @if($info_user->is_vip)<span class="admin-ribbon">VIP</span> @endif
        </div>
        <div class="online-user-jeux">
            <font>Jeux:</font>
            @foreach($info_user->jeux as $jeux)
                {!! HTML::image($jeux) !!}
            @endforeach
        </div>
    </div>
    <div class="clear-float"></div>
    <div class="bottom">
        <a href="#" class="com-control"><i class="fa fa-envelope"></i>Message privé</a>
        <a href="{{ route('userProfil',['name' => str_slug($info_user->pseudo), 'id' => $info_user->id]) }}" class="com-control"><i class="fa fa-file-text-o"></i>Voir le profil</a>
    </div>
</div>