app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'IndexController@index');
Route::get('/home', 'IndexController@index');


// Authentication routes...
Route::get('auth/', 'Auth\AuthController@index');
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');


// Compte
Route::get('/compte', array (
    'uses' => 'CompteController@index'
));
Route::get('/compte/modifier', array (
    'uses' => 'CompteController@edit'
));
Route::post('/compte/modifier', array (
    'uses' => 'CompteController@update'
));
Route::get('/compte/avatar', array (
    'uses' => 'CompteController@avatar'
));
Route::post('/compte/avatar', array (
    'uses' => 'CompteController@Postavatar'
));
Route::get('/compte/avatar/use/{id}', array (
    'uses' => 'CompteController@changeAvatar'
));
//info tooltip
Route::get('/info-tooltip/{id}', array (
    'uses' => 'ProfilController@infoTooltip',
));



// bajail
Route::get('/bajail', array (
    'uses' => 'BajailController@index'
));
Route::get('/bajail/charte', array (
    'uses' => 'BajailController@index_charte'
));
Route::get('/bajail/regles', array (
    'uses' => 'BajailController@index_regles'
));




// admin
Route::get('/bajail/admin', array (
    'uses' => 'BajailController@index_admin'
));
Route::get('/bajail/admin/devenir-admin', array (
    'uses' => 'DevenirAdminController@index'
));
Route::post('/bajail/admin/devenir-admin', array (
    'uses' => 'DevenirAdminController@post'
));
Route::get('/bajail/admin/devenir-admin/confirmation', array (
    'uses' => 'DevenirAdminController@confirmation',
    'middleware' => 'auth'
));




// test des règles
Route::get('/bajail/regles/test', array (
    'uses' => 'BajailController@index_test',
    'middleware' => 'auth'
));
Route::post('/bajail/regles/test', array (
    'uses' => 'BajailController@verifTest',
    'middleware' => 'auth'
));



// vocal
Route::get('/tchat', array (
    'uses' => 'tchatController@index'
));


// vip
Route::get('/bajail/vip', array (
    'uses' => 'VipController@index'
));

Route::post('/bajail/vip/confirmation', array (
    'uses' => 'VipController@store',
    'middleware' => 'auth'
));


// nems
Route::get('/team-nems', array (
    'uses' => 'NemsController@index'
));
Route::get('/team-nems/liste', array (
    'uses' => 'NemsController@liste'
));


// promo
Route::get('/promo', array (
    'uses' => 'PromoController@index'
));
// promo
Route::get('/promo/acheter/{id}', array (
    'uses' => 'PromoController@acheter',
    'middleware' => 'auth'
));

Route::get('/promo/acheter/{id}/valider', array (
    'uses' => 'PromoController@valider',
    'as' => 'acheterPromo',
    'middleware' => 'auth'
));



//steamid
Route::get('/compte/steamid', array (
    'uses' => 'CompteController@steamid',
    'middleware' => 'auth'
));

Route::post('/compte/steamid', array (
    'uses' => 'CompteController@steamidPost',
    'middleware' => 'auth'
));

Route::post('/compte/steamid/verif', array (
    'uses' => 'CompteController@steamidVerif',
    'middleware' => 'auth'
));


//profil
Route::get('/profil/{id}-{name}', array (
    'uses' => 'ProfilController@index',
    'as' => 'userProfil'
));



//jetons
Route::get('/jetons', array (
    'uses' => 'JetonsController@index',
));
Route::any('/jetons/check', array (
    'uses' => 'JetonsController@check',
));
Route::get('/jetons/valide', array (
    'uses' => 'JetonsController@valide',
));
Route::any('/jetons/valide2', array (
    'uses' => 'JetonsController@validestarpass',
));
Route::get('/jetons/erreur', array (
    'uses' => 'JetonsController@erreur',
));
Route::get('/jetons/paypal-trait', array (
    'uses' => 'JetonsController@checkPaypal',
));
Route::post('/jetons/paypal-trait', array (
    'uses' => 'JetonsController@checkPaypal',
));
Route::post('/jetons/valide-paypal', array (
    'uses' => 'JetonsController@validePaypal',
));


// coins
Route::get('/coins', array (
    'uses' => 'CoinsController@index',
));
Route::post('/coins', array (
    'uses' => 'CoinsController@post',
));



Route::group(['middleware' => ['auth']], function () {
    //forum, liste des forums
    Route::get('/forum', array (
        'uses' => 'ForumController@index'
    ));
// liste des forum dans une categorie
    Route::get('/forum/category/{id}-{name}', array (
        'uses' => 'ForumController@topicsList',
        'as' => 'forumCategory'
    ));

// créer un topic dans une catégorie
    Route::get('/forum/category/{id}-{name}/create', array (
        'uses' => 'ForumController@createTopic',
        'as' => 'createTopic',
        'middleware' => 'auth'
    ));
    Route::post('/forum/category/{id}-{name}/create', array (
        'uses' => 'ForumController@createTopicPost',
        'as' => 'createTopicPost',
        'middleware' => 'auth'
    ));


// affiche un topic
    Route::get('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}', array (
        'uses' => 'ForumController@topics',
        'as' => 'forumTopic'
    ));
// répondre par ajax a un topic (quick reply)
    Route::post('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}', array (
        'uses' => 'ForumController@replyTopicFast',
        'as' => 'forumTopic'
    ));

// lock topic
    Route::get('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}/lock', array (
        'uses' => 'ForumController@lockTopic',
        'as' => 'lockTopic',
        'middleware' => 'auth'
    ));

// pinned un topic
    Route::get('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}/pinned', array (
        'uses' => 'ForumController@pinnedTopic',
        'as' => 'pinnedTopic',
        'middleware' => 'auth'
    ));


// affiche la page de réponse normale a un topic
    Route::get('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}/reply', array (
        'uses' => 'ForumController@replyTopics',
        'as' => 'replyTopic',
        'middleware' => 'auth'
    ));
// répondre normalement a un topic
    Route::post('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}/reply', array (
        'uses' => 'ForumController@postReplyTopics',
        'middleware' => 'auth',
        'as' => 'replyTopicPost'
    ));


// répondre a un post en particulier d'un topic
    Route::get('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}/reply/{post_id}', array (
        'uses' => 'ForumController@replyTopicsWithQuote',
        'as' => 'replyTopicWithQuote',
        'middleware' => 'auth'
    ));

    Route::post('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}/reply/{post_id}', array (
        'uses' => 'ForumController@postReplyTopics',
        'middleware' => 'auth'
    ));


// modifier le post d'un topic
    Route::get('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}/edit/{post_id}', array (
        'uses' => 'ForumController@EditPost',
        'as' => 'EditPost',
        'middleware' => 'auth'
    ));
// modifier le post d'un topic
    Route::post('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}/edit/{post_id}', array (
        'uses' => 'ForumController@EditPostSend',
        'as' => 'EditPostSend',
        'middleware' => 'auth'
    ));


    // supprime un post
    Route::get('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}/remove/{post_id}', array (
        'uses' => 'ForumController@RemovePost',
        'as' => 'removePost',
        'middleware' => 'auth'
    ));
});

app/ForumPosts.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use tidy;

class ForumPosts extends Model
{
    public function user()
    {
        return $this->belongsTo('App\User','users_id');
    }

    public function forum_topics()
    {
        return $this->belongsTo('App\ForumTopics','forum_topics_id','');
    }

    public function getDateAttribute(){
        $date = new Carbon($this->created_at);
        return $date->format('d/m/Y').' à '.$date->format('H:i');
    }
    public function getDateShortAttribute(){
        $date = new Carbon($this->created_at);
        return $date->format('d/m/Y');
    }

    public function getUpdatedAtAttribute($value){
        $date = new Carbon($value);
        return $date->format('d/m/Y').' à '.$date->format('H:i');
    }
    public function getMessageShortAttribute(){
        return $this->get_words($this->message);
    }

    function get_words($sentence, $count = 50) {
        $pieces = explode(" ", $sentence);
        $first_part = implode(" ", array_splice($pieces, 0, $count)).'...';
        $tidy = new Tidy();
        $tidy->parseString($first_part);
        $tidy->cleanRepair();

        echo $tidy;
    }
}

resources/views/forum/create_topic.blade.php
@extends('layout/doublepage')

@section('title')
    Créer un topic
@endsection
@section('pagename')
    Créer un topic
@endsection

@section('sub_pagename','Forum')
@section('sub_pagename_link',url('/forum'))

@section('sub_pagename_2')
    Forum {{ $category->nom }}
@endsection
@section('sub_pagename_link_2')
    {{ route('forumCategory',[$category->id,str_slug($category->nom)]) }}
@endsection


@section('content')


    <div class="forum-block">

        <h2><span>Créer un topic</span></h2>




        @if(count($errors->all()) > 0)
            <div class="row">
                <div class="col-sm-12">
                    <div class="info-message" style="background-color: #a24026;">
                        <a class="close-info" href="#">
                            <i class="fa fa-times"></i>
                        </a>
                        <p>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                        </p>
                    </div>
                </div>
            </div>
        @endif



        <div class="content-padding full-reply">

            {!! Form::open() !!}
            <div class="reply-box">

                <div class="reply-textarea">
                    <form action="" method="get">
                        <div class="respond-input">
                            <div class="da-customs">
                                <input type="checkbox" name="pinned" id="pinned" />
                                <label for="pinned">Topic épinglé</label>
                            </div>
                            <input id="title" name="title" type="text" value="{{old('title')}}" placeholder="Sujet du topic" />
                        </div>
                        <div class="respond-textarea">
                           <textarea id="ckeditor_full" name="comment-text" class="ckeditor">{{old('comment-text')}}</textarea>
                        </div>
                        <div class="respond-submit">
                            <!--<a href="forum-create.html#preview-post" class="newdefbutton">Preview</a>-->
                            <input id="reply_post" type="submit" name="send" value="Créer ce topic">
                        </div>
                    </form>
                </div>
            </div>
            {!! Form::close() !!}
        </div>

    </div>

@endsection

resources/views/forum/forum_category_show.blade.php
<!-- BEGIN .forum-link -->
<div class="forum-link">
    <a href="{{ route('forumCategory',[$forum->id,str_slug($forum->nom)]) }}">
        @if($forum->is_read)
            <i class="forum-icon">
                <i class="fa {{$forum->icone}}"></i>
            </i>
        @else
            <i class="forum-icon new">
                <span>new</span>
                <i class="fa {{$forum->icone}}"></i>
            </i>
        @endif
        <strong>{{$forum->nom}}</strong>
        <span>{!! $forum->description !!}</span>
    </a>

    <div class="right">
        <div class="forum-numbers">
            <span>{{$forum->nb_topics}} Topics</span>
            <span>{{$forum->nb_posts}} Post</span>
        </div>
        <div class="forum-recent">
            @if($forum->last_topic_edit != null )
                <a href="{{ route('userProfil',['id' => $forum->users[0]->id,'name' => str_slug($forum->users[0]->pseudo)]) }}" class="avatar @if($forum->users[0]->isOnline) online @endif">
                    <span class="wrapimg">

                        @if($forum->users[0]->avatar == null)
                            {!! HTML::image('/uploads/tux-counter.png','',['class' => 'img-responsive','width' => '45', 'height' => '45']) !!}
                        @else
                            <img width="45" height="45" src="{{url('/')}}/uploads/{{$forum->users[0]->avatar}}" alt="{{$forum->users[0]->pseudo}} avatar"/>
                        @endif
                    </span>
                </a>

                <span>
                    <a href="{{ route('forumTopic',[$forum->id,str_slug($forum->nom),$forum->forumtopics[0]->id,str_slug($forum->forumtopics[0]->title)]) }}">{{ $forum->forumtopics[0]->title }}</a>
                    <span class="f-date">{{ $forum->forumtopics[0]->updated_at }}</span>
                    <span class="f-user-link"><a href="{{ route('userProfil',['id' => $forum->users[0]->id,'name' => str_slug($forum->users[0]->pseudo)]) }}"><strong>{{ $forum->users[0]->pseudo }}</strong></a></span>
                </span>
            @else
                <span class="f-no-posts">No thread to show</span>
            @endif
        </div>
    </div>
    <!-- BEGIN .forum-link -->
</div>

resources/views/forum/forum_list_topics.blade.php
<!-- BEGIN .thread-link -->
<div class="thread-link @if(in_array($topic->id,$topics_view)) thread-read @else thread-unread @endif @if($topic->pinned) thread-sticky @endif @if($topic->lock) thread-locked @endif ">
    <a href="{{ route('forumTopic',[$category->id,str_slug($category->nom),$topic->id,str_slug($topic->title)]) }}">
        <i class="forum-icon strike-tooltip" title="Topic">
            <i class="fa fa-comments-o"></i>
        </i>

        <span>
            @if($topic->pinned)
                <i class="sticky">Pinned</i>
            @endif
            @if($topic->lock)
                    <i class="thr-closed">Closed</i>
            @endif

            {{ $topic->title }}

            @if($topic->lock)<i class="fa fa-lock"></i>@endif
        </span>
    </a>
    <div class="thread-author">
        <span class="f-user-link">
            <a href="{{ route('userProfil',['id' => $topic->users->id,'name' => str_slug($topic->users->pseudo)]) }}">
                <strong>{{ $topic->users->pseudo }}</strong>
            </a>
        </span>
    </div>
    <div class="thread-replies">
        <span>{{ $topic->nb_posts -1 }}</span>
    </div>
    <div class="thread-views">
        <span>{{ $topic->nb_views }}</span>
    </div>
    <div class="thread-last">
        @if($topic->last_answers_name ==  null)
            <span class="no-response">No answers</span>
        @else
            <span class="f-user-link"><strong>{{ $topic->last_answers_name }}</strong></span>
            <span class="t-date">{{ $topic->updated_at }}</span>
        @endif
    </div>
    <!-- END .thread-link -->
</div>

resources/views/forum/forum_onepost_show.blade.php
<!-- BEGIN .forum-thread -->
<div class="forum-thread last">
    <!-- BEGIN .forum-post -->
    <div class="forum-post " id="post-" >
        <div class="user-block">
            <div class="avatar @if($post->user->isOnline) online @endif user-tooltip">
                @if($post->user->avatar == null)
                    {!! HTML::image('/uploads/tux-counter.png','',['class' => 'img-responsive','width' => '39', 'height' => '39']) !!}
                @else
                    <img src="{{url('/')}}/uploads/{{$post->user->avatar}}" alt="{{$post->user->pseudo}} avatar" width="39" height="39"  />
                @endif

                <?php $info_user = $post->user ?>

                @include('compte/user_tooltip_info')


            </div>
            <div class="user-account">
                <div>
                    <a href="user-single.html" class="forum-user user-tooltip"><b>{{$post->user->pseudo}}</b></a> <br/>
                    @if($post->user->is_nems)<span class="admin-ribbon">NemS</span> @endif
                    @if($post->user->is_admin)<span class="admin-ribbon">Admin</span> @endif
                    @if($post->user->is_vip)<span class="admin-ribbon">VIP</span> @endif
                    <br/>

                </div>

            </div>

            <div class="clear-float"></div>
        </div>
        <div class="post-text-block">

            {!! $post->message !!}

        </div>
        <div class="post-meta-block">
            <div>
                <a href="#post-{{$post->id}}">#</a> <span class="post-date">{{$post->date}}</span>
            </div>
            <!--<div class="bottom">
                <a href="#" class="defbutton admin-color"><i class="fa fa-trash-o"></i></a>
                <a href="#" class="defbutton admin-color"><i class="fa fa-pencil"></i></a>
                <a href="#quick-reply" class="defbutton scroll"><i class="fa fa-comment-o"></i>Reply</a>
            </div>-->
        </div>
        <!-- END .forum-post -->
    </div>

    <!-- END .forum-thread -->
</div>

resources/views/forum/forum_post_edit.blade.php
@extends('layout/doublepage')

@section('title')
    {{ $topic->title  }}
@endsection
@section('pagename')
    {{ $topic->title  }}
@endsection

@section('sub_pagename','Forum')
@section('sub_pagename_link',url('/forum'))

@section('sub_pagename_2')
    Forum {{ $category->nom }}
@endsection
@section('sub_pagename_link_2')
    {{ route('forumCategory',[$category->id,str_slug($category->nom)]) }}
@endsection


@section('content')


    <div class="forum-block">

        <h2><span>@if($topic->lock)<i class="fa fa-lock"></i>@endif Edit : {{ $topic->title  }}</span></h2>

        <div class="content-padding quick-reply" id="quick-reply">
            {!! Form::open() !!}

            <div class="reply-box" style="display: block">
                <div class="reply-textarea">
                    <form action="" method="get">
                        <div class="respond-textarea">
                            <textarea id="ckeditor_full" name="comment-text" class="ckeditor">
                                {!! $post_id_content !!}
                            </textarea>
                        </div>
                        <div class="respond-submit">
                            <!--<a href="forum-create.html#preview-post" class="newdefbutton">Preview</a>-->
                            <input id="reply_post" type="submit" name="send" value="Modifier ma réponse">
                        </div>
                    </form>
                </div>
            </div>

            {!! Form::close() !!}

        </div>

    </div>

@endsection

resources/views/forum/forum_post_reply.blade.php
@extends('layout/doublepage')

@section('title')
    {{ $topic->title  }}
@endsection
@section('pagename')
    {{ $topic->title  }}
@endsection

@section('sub_pagename','Forum')
@section('sub_pagename_link',url('/forum'))

@section('sub_pagename_2')
    Forum {{ $category->nom }}
@endsection
@section('sub_pagename_link_2')
    {{ route('forumCategory',[$category->id,str_slug($category->nom)]) }}
@endsection


@section('content')


    <div class="forum-block">

        <h2><span>@if($topic->lock)<i class="fa fa-lock"></i>@endif Reply : {{ $topic->title  }}</span></h2>

        <div class="content-padding quick-reply" id="quick-reply">
            {!! Form::open() !!}

            <div class="reply-box" style="display: block">
                <div class="reply-textarea">
                    <form action="" method="get">
                        <div class="respond-textarea">
                            <textarea id="ckeditor_full" name="comment-text" class="ckeditor">
                                @if($post_id_content != null)
                                    <blockquote>{!! $post_id_content !!}</blockquote>
                                @endif
                                <p></p>
                            </textarea>
                        </div>
                        <div class="respond-submit">
                            <!--<a href="forum-create.html#preview-post" class="newdefbutton">Preview</a>-->
                            <input id="reply_post" type="submit" name="send" value="Poster ma réponse">
                        </div>
                    </form>
                </div>
            </div>

            {!! Form::close() !!}

        </div>

        <div id="forumPostsList">

            @foreach($posts as $key => $post)
                @include('forum/forum_post_show')
            @endforeach

        </div>

    </div>

@endsection

resources/views/forum/forum_post_show.blade.php
<!-- BEGIN .forum-thread -->
<div class="forum-thread">
    <!-- BEGIN .forum-post -->
    <div class="forum-post" id="post-{{$post->id}}">
        <div class="user-block">
            <div class="avatar @if($post->user->isOnline) online @endif ">
                <a href="{{ route('userProfil',['id' => $post->user->id,'name' => str_slug($post->user->pseudo)]) }}">
                    @if($post->user->avatar == null)
                        {!! HTML::image('/uploads/tux-counter.png','',['class' => 'img-responsive','width' => '39', 'height' => '39']) !!}
                    @else
                        <img src="{{url('/')}}/uploads/{{$post->user->avatar}}" alt="{{$post->user->pseudo}} avatar" width="39" height="39"  />
                    @endif
                </a>
            </div>
            <div class="user-account">
                <div>
                    <a href="{{ route('userProfil',['id' => $post->user->id,'name' => str_slug($post->user->pseudo)]) }}" class="forum-user">
                        <b>{{$post->user->pseudo}}</b>
                    </a> <br/>
                    @if($post->user->is_nems)<span class="admin-ribbon">NemS</span> @endif
                    @if($post->user->is_admin)<span class="admin-ribbon">Admin</span> @endif
                    @if($post->user->is_vip)<span class="admin-ribbon">VIP</span> @endif
                    <br/>

                </div>

            </div>

            <div class="clear-float"></div>
        </div>
        <div class="post-text-block">

            {!! $post->message !!}

            @if($post->is_edit)
                <div class="comment-edited">
                    <span>
                    <i class="fa fa-pencil"></i>
                    Modifié par
                        <b>{{$post->editor_name}}</b>
                        le
                    {{ $post->updated_at }}
                    </span>
                </div>
            @endif

        </div>
        <div class="post-meta-block">
            <div>
                <a href="#post-{{$post->id}}">#{{$key+1}}</a>
            </div>
            <div>
                <span class="post-date">{{$post->date}}</span>
            </div>
            <div class="bottom">
                @if(!$topic->lock or $user->is_modo)
                    <!--<a href="#" class="defbutton admin-color"><i class="fa fa-trash-o"></i></a>-->
                    @if($post->user->id == $user->id || $user->is_modo)
                        <a href="{{ route('EditPost',[$category->id,str_slug($category->nom),$topic->id,str_slug($topic->title),$post->id]) }}" class="defbutton admin-color"><i class="fa fa-pencil"></i></a>
                    @endif
                    @if($post->user->id == $user->id || $user->is_modo)
                        <a class="defbutton admin-color" href="{{ route('removePost',[$category->id,str_slug($category->nom),$topic->id,str_slug($topic->title),$post->id]) }} }}">
                            <i class="fa fa-trash-o"></i>
                        </a>
                    @endif
                    <a href="{{ route('replyTopicWithQuote',[$category->id,str_slug($category->nom),$topic->id,str_slug($topic->title),$post->id]) }}" class="defbutton"><i class="fa fa-comment-o"></i>Répondre</a>

                @endif
            </div>
        </div>
        <!-- END .forum-post -->
    </div>
    <!-- END .forum-thread -->
</div>

resources/views/forum/index.blade.php
@extends('layout/doublepage')

@section('title','Forum de la team')
@section('pagename','Forum')


@section('content')


    <div class="forum-block">

        <h2><span>La team Nemesis Spirit</span></h2>

        @include('messages/error')

        <!-- BEGIN .forum-group -->
        <div class="forum-group">

            @foreach($forumCategory_nems as $forum)
                @include('forum/forum_category_show')
            @endforeach


            <!-- END .forum-group -->
        </div>

        <h2><span>Le Bajail</span></h2>

        <!-- BEGIN .forum-group -->
        <div class="forum-group">

            @foreach($forumCategory_bajail as $forum)
                @include('forum/forum_category_show')
                @endforeach


                        <!-- END .forum-group -->
        </div>

        <h2><span>Divers / Autres jeux</span></h2>

        <!-- BEGIN .forum-group -->
        <div class="forum-group">

            @foreach($forumCategory_divers as $forum)
                @include('forum/forum_category_show')
                @endforeach


                        <!-- END .forum-group -->
        </div>

    </div>

@endsection

resources/views/forum/topic.blade.php
@extends('layout/doublepage')

@section('title')
    {{ $topic->title  }}
@endsection
@section('pagename')
    {{ $topic->title  }}
@endsection

@section('sub_pagename','Forum')
@section('sub_pagename_link',url('/forum'))

@section('sub_pagename_2')
    Forum {{ $category->nom }}
@endsection
@section('sub_pagename_link_2')
    {{ route('forumCategory',[$category->id,str_slug($category->nom)]) }}
@endsection


@section('content')


    <div class="forum-block">

        <h2><span>@if($topic->lock)<i class="fa fa-lock"></i>@endif{{ $topic->title  }}</span></h2>

        @include('messages/success')

        <div class="content-padding">
            <div class="forum-description">
                <div class="topic-right right">
                    @if($topic->lock) <span><i class="fa fa-unlock-alt"></i>Sujet fermé</span> @endif
                    <span>{{ $topic->nb_posts }} Posts</span>
                </div>

                @if(!$topic->lock or $user->is_modo)
                    <a href="{{ route('replyTopic',[$category->id,str_slug($category->nom),$topic->id,str_slug($topic->title)]) }}" class="newdefbutton margin-right"><i class="fa fa-comment-o"></i>Répondre</a>
                @endif

                @if(Auth::user()->is_modo)
                    <a class="newdefbutton margin-right admin-color" href="{{ route('lockTopic',[$category->id,str_slug($category->nom),$topic->id,str_slug($topic->title)]) }}">
                        <i class="fa fa-unlock"></i>
                        @if($topic->lock == false) Fermé ce topic @endif
                        @if($topic->lock == true) Ouvrir ce topic @endif
                    </a>
                    <a class="newdefbutton margin-right admin-color" href="{{ route('pinnedTopic',[$category->id,str_slug($category->nom),$topic->id,str_slug($topic->title)]) }}">
                        <i class="fa fa-level-up"></i>
                        @if($topic->pinned == false) Pin ce topic @endif
                        @if($topic->pinned == true) Unpin topic @endif
                    </a>
                @endif


            </div>
        </div>

        <div id="forumPostsList">

        @foreach($posts as $key => $post)
            @include('forum/forum_post_show')
        @endforeach

        </div>





        <div class="content-padding quick-reply" id="quick-reply">
            <div class="forum-description">
                @if(!$topic->lock or $user->is_modo)
                    <a href="#quick-reply" class="newdefbutton"><i class="fa fa-comment-o"></i>Réponse rapide</a>
                    <a style="margin-left: 15px" href="{{ route('replyTopic',[$category->id,str_slug($category->nom),$topic->id,str_slug($topic->title)]) }}" class="newdefbutton"><i class="fa fa-comment-o"></i>Répondre</a>
                @endif
            </div>
            {!! Form::open(array('id' => 'quick_reply_form', 'url' => route('forumTopic',[$category->id,str_slug($category->nom),$topic->id,str_slug($topic->title)]))) !!}

            <div class="reply-box">
                <div class="reply-textarea">
                    <form action="" method="get">
                        <div class="respond-textarea">
                                <textarea id="ckeditor" name="comment-text" class="ckeditor"></textarea>
                        </div>
                        <div class="respond-submit">
                            <!--<a href="forum-create.html#preview-post" class="newdefbutton">Preview</a>-->
                            <a href="{{ route('replyTopic',[$category->id,str_slug($category->nom),$topic->id,str_slug($topic->title)]) }}" class="newdefbutton">Full version</a>
                            <input id="quick_reply_post" type="submit" name="send" value="Envoyé ma réponse">
                        </div>
                    </form>
                </div>
            </div>

            {!! Form::close() !!}

        </div>

        <div class="content-padding">
            <div class="forum-description">
                <div class="topic-right right">
                    @if($topic->lock)<span><i class="fa fa-unlock-alt"></i>Sujet fermé</span>@endif
                        <span>{{ $topic->nb_posts }} Posts</span>
                </div>
            </div>
        </div>

    </div>


@endsection