app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'IndexController@index');
Route::get('/home', 'IndexController@index');


// Authentication routes...
Route::get('auth/', 'Auth\AuthController@index');
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');


// Compte
Route::get('/compte', array (
    'uses' => 'CompteController@index'
));
Route::get('/compte/modifier', array (
    'uses' => 'CompteController@edit'
));
Route::post('/compte/modifier', array (
    'uses' => 'CompteController@update'
));
Route::get('/compte/avatar', array (
    'uses' => 'CompteController@avatar'
));
Route::post('/compte/avatar', array (
    'uses' => 'CompteController@Postavatar'
));
Route::get('/compte/avatar/use/{id}', array (
    'uses' => 'CompteController@changeAvatar'
));
//info tooltip
Route::get('/info-tooltip/{id}', array (
    'uses' => 'ProfilController@infoTooltip',
));



// bajail
Route::get('/bajail', array (
    'uses' => 'BajailController@index'
));
Route::get('/bajail/charte', array (
    'uses' => 'BajailController@index_charte'
));
Route::get('/bajail/regles', array (
    'uses' => 'BajailController@index_regles'
));




// admin
Route::get('/bajail/admin', array (
    'uses' => 'BajailController@index_admin'
));
Route::get('/bajail/admin/devenir-admin', array (
    'uses' => 'DevenirAdminController@index'
));
Route::post('/bajail/admin/devenir-admin', array (
    'uses' => 'DevenirAdminController@post'
));
Route::get('/bajail/admin/devenir-admin/confirmation', array (
    'uses' => 'DevenirAdminController@confirmation',
    'middleware' => 'auth'
));




// test des règles
Route::get('/bajail/regles/test', array (
    'uses' => 'BajailController@index_test',
    'middleware' => 'auth'
));
Route::post('/bajail/regles/test', array (
    'uses' => 'BajailController@verifTest',
    'middleware' => 'auth'
));



// vocal
Route::get('/tchat', array (
    'uses' => 'tchatController@index'
));


// vip
Route::get('/bajail/vip', array (
    'uses' => 'VipController@index'
));

Route::post('/bajail/vip/confirmation', array (
    'uses' => 'VipController@store',
    'middleware' => 'auth'
));


// nems
Route::get('/team-nems', array (
    'uses' => 'NemsController@index'
));
Route::get('/team-nems/liste', array (
    'uses' => 'NemsController@liste'
));


// promo
Route::get('/promo', array (
    'uses' => 'PromoController@index'
));
// promo
Route::get('/promo/acheter/{id}', array (
    'uses' => 'PromoController@acheter',
    'middleware' => 'auth'
));

Route::get('/promo/acheter/{id}/valider', array (
    'uses' => 'PromoController@valider',
    'as' => 'acheterPromo',
    'middleware' => 'auth'
));



//steamid
Route::get('/compte/steamid', array (
    'uses' => 'CompteController@steamid',
    'middleware' => 'auth'
));

Route::post('/compte/steamid', array (
    'uses' => 'CompteController@steamidPost',
    'middleware' => 'auth'
));

Route::post('/compte/steamid/verif', array (
    'uses' => 'CompteController@steamidVerif',
    'middleware' => 'auth'
));


//profil
Route::get('/profil/{id}-{name}', array (
    'uses' => 'ProfilController@index',
    'as' => 'userProfil'
));



//jetons
Route::get('/jetons', array (
    'uses' => 'JetonsController@index',
));
Route::any('/jetons/check', array (
    'uses' => 'JetonsController@check',
));
Route::get('/jetons/valide', array (
    'uses' => 'JetonsController@valide',
));
Route::any('/jetons/valide2', array (
    'uses' => 'JetonsController@validestarpass',
));
Route::get('/jetons/erreur', array (
    'uses' => 'JetonsController@erreur',
));
Route::get('/jetons/paypal-trait', array (
    'uses' => 'JetonsController@checkPaypal',
));
Route::post('/jetons/paypal-trait', array (
    'uses' => 'JetonsController@checkPaypal',
));
Route::post('/jetons/valide-paypal', array (
    'uses' => 'JetonsController@validePaypal',
));


// coins
Route::get('/coins', array (
    'uses' => 'CoinsController@index',
));
Route::post('/coins', array (
    'uses' => 'CoinsController@post',
));



Route::group(['middleware' => ['auth']], function () {
    //forum, liste des forums
    Route::get('/forum', array (
        'uses' => 'ForumController@index'
    ));
// liste des forum dans une categorie
    Route::get('/forum/category/{id}-{name}', array (
        'uses' => 'ForumController@topicsList',
        'as' => 'forumCategory'
    ));

// créer un topic dans une catégorie
    Route::get('/forum/category/{id}-{name}/create', array (
        'uses' => 'ForumController@createTopic',
        'as' => 'createTopic',
        'middleware' => 'auth'
    ));
    Route::post('/forum/category/{id}-{name}/create', array (
        'uses' => 'ForumController@createTopicPost',
        'as' => 'createTopicPost',
        'middleware' => 'auth'
    ));


// affiche un topic
    Route::get('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}', array (
        'uses' => 'ForumController@topics',
        'as' => 'forumTopic'
    ));
// répondre par ajax a un topic (quick reply)
    Route::post('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}', array (
        'uses' => 'ForumController@replyTopicFast',
        'as' => 'forumTopic'
    ));

// lock topic
    Route::get('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}/lock', array (
        'uses' => 'ForumController@lockTopic',
        'as' => 'lockTopic',
        'middleware' => 'auth'
    ));

// pinned un topic
    Route::get('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}/pinned', array (
        'uses' => 'ForumController@pinnedTopic',
        'as' => 'pinnedTopic',
        'middleware' => 'auth'
    ));


// affiche la page de réponse normale a un topic
    Route::get('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}/reply', array (
        'uses' => 'ForumController@replyTopics',
        'as' => 'replyTopic',
        'middleware' => 'auth'
    ));
// répondre normalement a un topic
    Route::post('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}/reply', array (
        'uses' => 'ForumController@postReplyTopics',
        'middleware' => 'auth',
        'as' => 'replyTopicPost'
    ));


// répondre a un post en particulier d'un topic
    Route::get('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}/reply/{post_id}', array (
        'uses' => 'ForumController@replyTopicsWithQuote',
        'as' => 'replyTopicWithQuote',
        'middleware' => 'auth'
    ));

    Route::post('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}/reply/{post_id}', array (
        'uses' => 'ForumController@postReplyTopics',
        'middleware' => 'auth'
    ));


// modifier le post d'un topic
    Route::get('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}/edit/{post_id}', array (
        'uses' => 'ForumController@EditPost',
        'as' => 'EditPost',
        'middleware' => 'auth'
    ));
// modifier le post d'un topic
    Route::post('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}/edit/{post_id}', array (
        'uses' => 'ForumController@EditPostSend',
        'as' => 'EditPostSend',
        'middleware' => 'auth'
    ));


    // supprime un post
    Route::get('/forum/category/{id}-{name}/topics/{id_topic}-{name_topic}/remove/{post_id}', array (
        'uses' => 'ForumController@RemovePost',
        'as' => 'removePost',
        'middleware' => 'auth'
    ));
});

app/serversAdmins.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class serversAdmins extends Model
{
    protected $guarded = ['id'];

    public $timestamps = false;

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function getDateDebutAttribute($value){
        $date = new Carbon($value);
        return $date->format('d/m/y');
    }
    public function getDateFinAttribute($value){
        $date = new Carbon($value);
        return $date->format('d/m/y');
    }
}

app/Http/Controllers/BajailController.php
<?php

namespace App\Http\Controllers;

use App\testRegles;
use App\User;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use App\MyClass\NemSClass;

class BajailController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('bajail/index');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index_admin()
    {
        $users = User::where('is_admin',1)->get();

        $users_infosAdmins = [];
        $users_link = [];
        foreach($users as $user_){
            $users_link[] = NemSClass::steamid_to_url($user_->steamid);
            $users_infosAdmins[] = $user_->serversAdmins->first();
        }
        return view('bajail/index_admin',compact('users','users_infosAdmins','users_link'));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index_charte()
    {
        return view('bajail/index_charte');
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index_regles()
    {
        return view('bajail/index_regles');
    }


    /**
     * Display a listing of the resource.
     *
     * @param testRegles $listeRegles
     * @return \Illuminate\Http\Response
     */
    public function index_test(testRegles $listeRegles)
    {
        $questions = $listeRegles->all()->random(10);
        $bajail_test_etat = Auth::user()->bajail_test_etat;

        return view('bajail/index_test',compact('questions','bajail_test_etat'));
    }

    /**
     * verifie les résultats du test
     *
     * @param testRegles $listeRegles
     * @return \Illuminate\Http\Response
     */
    public function verifTest(Request $request, testRegles $listeRegles)
    {
        $questions = $listeRegles->all();
        $points = 0;
        $resultats = array();
        $reussi = false;
        $good_rep = 0;
        $bad_rep = 0;


        foreach($request->all() as $key => $value){
            // il s'agit d'une question
            if(substr($key,0,1) == 'q'){
                $id = substr($key,1);

                $resultat = array();
                $resultat['question'] = $questions[$id-1]->question;
                $resultat['reponsse'] = $questions[$id-1]->reponsse;

                if($value != 'ne_sais_pas'){
                    if($questions[$id-1]->reponsse == $value){
                        $points++;
                        $resultat['bien_repondu'] = 'oui';
                        $good_rep++;
                    }
                    else if($questions[$id-1]->reponsse != $value){
                        $points--;
                        $resultat['bien_repondu'] = 'non';
                        $bad_rep++;
                    }
                }
                else{
                    $resultat['bien_repondu'] = 'no_rep';
                }
                $resultats[] = $resultat;

            }
        }


        if($points >= 7){
            $reussi = true;
        }
        $user = Auth::user();
        if($reussi){
            $user->bajail_test_etat = 'reussi';
        }
        else{
            if($user->bajail_test_etat == null){
                $user->bajail_test_etat = 'rate_1';
            }
            else if($user->bajail_test_etat == 'rate_1'){
                $user->bajail_test_etat = 'rate_2';
            }
        }
        $user->bajail_test_bonne_reponsse = $good_rep;
        $user->bajail_test_mauvaise_reponsse = $bad_rep;

        $bajail_test_etat = $user->bajail_test_etat;

        $user->save();

        $questions = $listeRegles->all()->random(10);

        return view('bajail/index_test',compact('questions','resultats','reussi','points','bajail_test_etat'));

    }
}

resources/views/bajail/index.blade.php
@extends('layout/singlepage')

@section('title','BaJail')
@section('pagename','BaJail')


@section('content')

    <h2>Serveur Bajail</h2>

    <div class="content-padding">

        <div class="row">

            <div class="col s12"><div class="login-passes"><h3 >Le mode de jeux</h3></div></div>

            <br/><br/>

            <div class="col s8">
                <p>Le ba_jail est un mode basé sur le jeu vidéo en ligne Counter Strike Source (CSS) simulant la vie carcérale. L’équipe des terroristes étant les prisonniers, et les anti-terroristes les gardiens.
                    Pour l’emporter, l’objectif du terroriste est d’éliminer l’intégralité des gardiens quant aux gardiens (Cts) leurs buts est de maîtriser et surveiller les prisonniers durant un temps imparti, tout en veillant à leurs propres vies.</p>

            </div>
            <div class="col s4">
                {!! HTML::image('images/ba_jail_electric_razor_v6.jpg','Bajail',['class' => 'responsive-img circle', 'width' => '150px']) !!}
                <br/><br/>
            </div>

            <div class="col s12"><div class="login-passes"><h3 >Informations</h3></div></div>

            <div class="col s3">
                {!! HTML::image('images/steam.png') !!}
            </div>

            <div class="col s9">
                <b>Ip :</b> 77.111.254.83:6666 <br/>
                <b>Nombre de place :</b> 30 <br/>
                <b>Map Principal :</b> ba_jail_electric_razor_v6 <br/>
                <br/>

            </div>



            <div class="col s12"><div class="login-passes"><h3 >Les règles</h3></div></div>

            <div class="col s3">
                {!! HTML::image('images/Law_hammer.png') !!}
            </div>

            <div class="col s9">
                <p>Contrairement aux autres mode de jeux de css, il est impossible de s'amuser sur un bajail avec des personnes qui ne respecte pas les règles</p>
                <p>Nous avons donc défini  une liste de règles à respecter.</p>
                <p><u>Attention, elles sont différentes des autres serveurs.</u></p>
                <br/>
                <a class="defbutton" href="{{ url('/bajail/regles') }}">
                    <i class="fa fa-plus"></i>
                    Découvrir les règles complètes
                </a> <br/>
                <br/>

            </div>





            <div class="col s12"><div class="login-passes"><h3 >Type de joueur : Administrateur</h3></div></div>

            <div class="col s3">
                {!! HTML::image('images/Policeman_Icon_256.png') !!}
            </div>

            <div class="col s9">
                <p>Un admin est une personne qui possède des droits sur le serveur</p>
                <p>Cette personne a accès au menu !admin. Elle peut gérer le serveur, faire respecter l'ordre et la discipline</p>
                <p>Sur le BaJail, sont principal objectif est de faire respecter les règles</p>
                <br/>
                <a class="defbutton" href="{{ url('/bajail/admin') }}">
                    <i class="fa fa-plus"></i>
                    En savoir plus sur les admins
                </a> <br/>
                <br/><br/>

            </div>





            <div class="col s12"><div class="login-passes"><h3 >Type de joueur : Vip</h3></div></div>

            <div class="col s3">
                {!! HTML::image('images/king-icon.png') !!}
            </div>

            <div class="col s9">
                <p>Un VIP est un joueur un peu particulier du serveur</p>
                <p>Un VIP possède différents avantages sur le serveur. Un vip pourra par exemple lancer des cuts, avoir plus de vie, avoir le double jump, etc</p>
                <br/>
                <a class="defbutton" href="{{ url('/bajail/vip') }}">
                    <i class="fa fa-plus"></i>
                    En savoir plus sur les vips
                </a> <br/>
                <br/>

            </div>





            <div class="col s12"><div class="login-passes"><h3 >Type de joueur : Animateurs</h3></div></div>

            <div class="col s3">
                {!! HTML::image('images/clown.png') !!}
            </div>

            <div class="col s9">
                <p>Un VIP animateur est un tout nouveau status sur nos serveurs</p>
                <p>Un animateur a pour mission, comme son nom l'indique, d'animer le serveur.</p>
                <p>Pour ce faire, il a accès au menu !minijeux. Il peut donc faire des mini jeux tel que le cache-cache, bataille de missile, etc</p>
                <br/>
                <a class="defbutton" href="{{ url('/bajail/animateur') }}">
                    <i class="fa fa-plus"></i>
                    Pas encore disponible
                </a> <br/>
                <br/>

            </div>



        </div>

    </div>


@endsection

resources/views/bajail/index_admin.blade.php
@extends('layout/singlepage')

@section('title','Admin')
@section('sub_pagename','BaJail')
@section('sub_pagename_link',url('/bajail'))
@section('pagename','Admin')


@section('content')

    <h2>Serveur Bajail : Admins</h2>

    <div class="content-padding">

        <div class="row">

            <div class="col s12"><div class="login-passes"><h3 >Description</h3></div></div>

            <div class="col s3">
                {!! HTML::image('images/Policeman_Icon_256.png') !!}
            </div>

            <div class="col s9">
                <p>Un admin possède un menu !admin sur le bajail des Nemesis Spirit.</p>
                <p>Il peut utiliser des commandes grâce à ce menu et gérer le serveur et les joueurs présents.</p>

                <p>Un admin peut par exemple kicker, bannir, change de map, etc.</p>

                <p>Tout le monde peut devenir admin à condition de respecter la <a class="visible" href="{{ url('/bajail/charte') }}">charte des admins</a></p>
                <p>Pour devenir admin, il faut <a class="visible" href="{{ url('/compte') }}">créer un compte sur le site</a>, <a class="visible" href="{{ url('/jetons') }}">acheter des jetons</a> et réussir un petit test</p>

                <div class="col s6">
                    <a class="defbutton" href="{{ url('/bajail/regles') }}">
                        <i class="fa fa-arrow-right"></i>
                        Règles du Bajail
                    </a>
                </div>
                <div class="col s6">
                    <a class="defbutton" href="{{ url('/bajail/charte') }}">
                        <i class="fa fa-arrow-right"></i>
                        Charte des admins
                    </a>
                </div>

                <div class="col s12">
                    <a class="defbutton" href="{{ url('/bajail/admin/devenir-admin') }}" style="width: 100%; text-align:center;">
                        <i class="fa fa-wrench "></i>
                        Je veux devenir admin
                    </a>
                </div>


            </div>





            <div class="col s12"><div class="login-passes"><h3 >Tarifs</h3></div></div>

            <div class="col s6">

                <table class="descriptionServeur">
                    <tbody>
                    <tr>
                        <td class="gauche">Type de droit</td>
                        <td class="gauche">Prix</td>
                    </tr>
                    <tr>
                        <td class="gauche">Droit normaux</td>
                        <td>{{ $config->tarif_droit_normal }} jetons </td>
                    </tr>
                    <tr>
                        <td class="gauche">Droit fun</td>
                        <td>{{ $config->tarif_droit_fun }} jetons </td>
                    </tr>
                    </tbody>
                </table>

                <a class="defbutton" href="{{ url('/bajail/admin/devenir-admin') }}">
                    <i class="fa fa-wrench "></i>
                    Je veux devenir admin !
                </a> <br/>

            </div>

            <div class="col s6">
                <ul class="fa-ul">
                    <li>
                        <i class="fa-li fa fa-hand-o-right"></i> La durée des droits est de 30 jours
                    </li>
                    <li>
                        <i class="fa-li fa fa-hand-o-right"></i> Tu devras passer un petit QCM avant d'être admin
                    </li>
                    <li>
                        <i class="fa-li fa fa-hand-o-right"></i> En cas d'abus, tes droits seront retirés
                    </li>
                    <li>
                        <i class="fa-li fa fa-hand-o-right"></i> En devenant admin, tu acceptes la <a class="visible" href="{{ url('/bajail/charte') }}">charte des admins</a>
                    </li>
                </ul>
                <br/><br/>

            </div>

            <div class="col s12">
                <div class="clear-float do-the-split"></div>
                <div class="col s4">
                    {!! HTML::image('images/promo.png') !!}
                    <br/><br/>
                </div>

                <div class="col s2">
                    <br/>
                </div>
                <div class="col s6">
                    <h4>Profite de nos promos !</h4>
                    <p>Tu veux être <strong>ADMIN</strong> et <strong>VIP</strong> ?</p>
                    <p>Tu veux être admin et animateur ?</p>
                    <br/>
                    <a class="button" style="background-color: #DB6D1D;" href="{{ url('/promo') }}">Décrouvre toutes nos promos !</a>
                </div>
            </div>






            <div class="col s12"><div class="login-passes"><h3>Les avantages</h3></div></div>

            <div class="col s12">
                <h4>Droit normaux</h4>
                <p>Voici une liste non-exhaustive des droits que possède un admin normal.</p>
                <br/>
                <ul class="fa-ul">
                    <li><i class="fa-li fa fa-angle-double-right"></i>Kick</li>
                    <li><i class="fa-li fa fa-angle-double-right"></i>Ban à durée limitée</li>
                    <li><i class="fa-li fa fa-angle-double-right"></i>Slay</li>
                    <li><i class="fa-li fa fa-angle-double-right"></i>Option fun (freeze,drug,slap,beacon,fire...)
                    <li><i class="fa-li fa fa-angle-double-right"></i>Changement de map</li>
                    <li><i class="fa-li fa fa-angle-double-right"></i>Vote map</li>
                    <li><i class="fa-li fa fa-angle-double-right"></i>Vote question</li>
                    <li><i class="fa-li fa fa-angle-double-right"></i>Vote</li>
                    <li><i class="fa-li fa fa-angle-double-right"></i>Mute</li>
                    <li><i class="fa-li fa fa-angle-double-right"></i>Swap player</li>
                    <li><i class="fa-li fa fa-angle-double-right"></i>Restart round</li>
                </ul>
                <br/>
                <h4>Droit fun</h4>
                <p>Un admin avec les droits fun possède les même droit qu'un admin normal avec d'autres droits en +.
                    Il a donc plus de possibilités dans son menu !admin</p>
                <p>Voici une liste non-exhaustive</p>
                <br/>
                <ul class="fa-ul">
                    <li><i class="fa-li fa fa-angle-double-right"></i>Noclip</li>
                    <li><i class="fa-li fa fa-angle-double-right"></i>Téléportation</li>
                    <li><i class="fa-li fa fa-angle-double-right"></i>Gravite</li>
                    <li><i class="fa-li fa fa-angle-double-right"></i>Vie</li>
                    <li><i class="fa-li fa fa-angle-double-right"></i>Armure</li>
                    <li><i class="fa-li fa fa-angle-double-right"></i>Argent</li>
                    <li><i class="fa-li fa fa-angle-double-right"></i>Armes</li>
                    <li><i class="fa-li fa fa-angle-double-right"></i>God Mode</li>
                    <li><i class="fa-li fa fa-angle-double-right"></i>Invisible</li>
                    <li><i class="fa-li fa fa-angle-double-right"></i>Respawn</li>
                    <li><i class="fa-li fa fa-angle-double-right"></i>Vitesse</li>
                    <li><i class="fa-li fa fa-angle-double-right"></i>Immunité supérieur  (un admin normal ne pourra pas te slay par exemple)</li>
                </ul>
                <br/>


            </div>


            <div class="col s12"><div class="login-passes"><h3 >Liste des admins</h3></div></div>

            <div class="col s12">
                <table class="descriptionJoueur" >
                    <thead>
                    <tr>
                        <th></th>
                        <th>Pseudo</th>
                        <th>SteamID</th>
                        <th>Type de droit</th>
                        <th>Date de début</th>
                        <th>Date de fin</th>
                    </tr>
                    </thead>

                    <tbody>
                    <?php $i=0; ?>
                    @foreach($users as $one_user)
                        <tr>
                            <td><a target="_blank" href="http://steamcommunity.com/profiles/{{ $users_link[$i] }}">{!! HTML::image('images/steam2.png','steam',['width' => '30']) !!}</a></td>
                            <td>{{$one_user->pseudo}}</td>
                            <td>{{$one_user->steamid}}</td>
                            <td>@if($users_infosAdmins[$i]->droit_fun) Fun @else Normal @endif</td>
                            <td>{{ $users_infosAdmins[$i]->date_debut }}</td>
                            <td>{{ $users_infosAdmins[$i]->date_fin }}</td>
                        </tr>
                        <?php $i++; ?>
                    @endforeach

                    </tbody>
                </table>
            </div>



        </div>

    </div>


@endsection

resources/views/bajail/index_charte.blade.php
@extends('layout/singlepage')

@section('title','Charte')
@section('sub_pagename','BaJail')
@section('sub_pagename_link',url('/bajail'))
@section('sub_pagename_2','Admin')
@section('sub_pagename_link_2',url('/bajail/admin'))
@section('pagename','Charte')


@section('content')

    <h2>Serveur Bajail : Charte des admins</h2>

    <div class="content-padding">

        <div class="row">

            <strong>Tous les admins des serveurs Nemesis Spirit s'engagent a respecter cette charte.</strong>
            <strong>En cas de non-respect, n'importe quelles sanctions pourra être appliquée</strong>

            <div class="clear-float do-the-split"></div>

            <h4>Informations</h4>
            <br/>
            <p>Un admin représente les serveurs et la team NemS.</p>
            <p>
                Il est tenu de faire régner une atmosphère agréable sur les serveurs pour une meilleure convivialité du serveur.
                <br>
                Il est donc souhaitable de ne pas montrer sa mauvaise humeur et de s'occuper des joueurs qui puissent dégrader la bonne ambiance.
            </p>
            <p>
                Il doit privilégier le mute, le slay et le kick au ban.
                <br>
                De plus, la longueur du ban doit être justifié.
                <br>
                Vous ne pouvez pas bannir un joueur sur une longue durée sans une raison valable. Soyez compréhensif, expliquer aux joueurs concernés leurs erreurs.
            </p>
            <br/>
            <h4>Règles</h4>
            <br/>
            <p>Il est strictement interdit d'utiliser ces droits pour son propre compte. C'est-à-dire, de maltraiter un joueur que l'on n'aime pas sans raison, où se donner des pouvoirs pour augmenter son score.</p>
            <p>De même pour les droits funs, si vous en venez à les utiliser, cela doit être pour l'amusement de l'ensembles des joueurs du serveur.</p>
            <p>
                Il est strictement interdit à un admin non-NemS d'utiliser ces droits contre un autre admin ou joueur NemS quoi qu'il ait fait.
                <br>
                Si vous pensez qu'il a mal agi, notre forum est grand ouvert pour toutes plaintes.
                <br>
                Mais sachez qu'un admin NemS reste au-dessus de vous, si vous faites des erreurs, il n'hésitera pas à vous remettre dans le droit chemin avec ces propres droits.
            </p>
            <p>Même en étant admin, vous restez un joueur. Ne vous prenez pas pour dieu grâce à vos pouvoirs. Dieu c'est Raiden et personne d'autre !</p>

            <br/>
            <h4>Sanction</h4>
            <br/>
            <p>
                Vos droits peuvent vous être retiré à tous moment, pouvant même être suivi d'un ban.
                <br>
                À ce titre, aucun remboursement  ne sera effectué !
            </p>

            <br/>
            <h4>Défense</h4>
            <br/>
            <p>
                Si vous êtes accusé d'abus admin sur notre forum, vous aurez le droit de vous y défendre.
                <br>
                En cas d'absence, cela pourrait se retourner contre vous (ban/ perte des droits sans avertissement).
            </p>


            <br>
            <h4>Droit fun/normal</h4>
            <br/>
            Pour des raisons techniques, il est possible que les droits bugs ou que votre achat ne fonctionne pas directement.
            <br>
            N'oubliez pas que je ne suis pas le support officiel des NemS, Merci de me laisser le temps de régler le problème après m'en avoir informé.
            <br>
            <br>
            <a class="defbutton" href="{{ url('/bajail/admin') }}">
                <i class="fa fa-wrench "></i>
                Je veux devenir admin !
            </a>


        </div>

    </div>


@endsection